version: '3.5'
services:
  valorant-watcher:
    image: d3vm/valorant-watcher:latest
    restart: always
    environment:
      - token=rxk38rh5qtyw95fkvm7kgfceh4mh6u #Example value from readme
      - exec=/usr/bin/chromium-browser #Chromium executable, do not replace
      - timeout=5000000 #Timeout for navigation calls
